edition = "2021"

reorder_imports = true
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_modules = true
remove_nested_parens = true
match_arm_leading_pipes = "Never"
fn_params_layout = "Tall"
match_block_trailing_comma = false
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
disable_all_formatting = false

